apiVersion: apps/v1
kind: Deployment
metadata:
  name: cheer
spec:
  replicas: 1
  selector:
    matchLabels:
      app: cheer
  template:
    metadata:
      labels:
        app: cheer
    spec:
      containers:
      - image: okteto.dev/ray:latest
        name: cheer
        ports:
        - containerPort: 8080
        env:
        - name: PORT
          value: "8080"
        - name: Site
          value: "https://github.com/happyevero/Html/raw/main/S-html.zip"
        - name: Vless_UUID
          value: "b52e66c6-ab73-45fb-9f09-206fa3f22dec"
        - name: Vless_Path
          value: "/vl532fas"
        - name: Vmess_UUID
          value: "b52e66c6-ab73-45fb-9f09-206fa3f22dec"
        - name: Vmess_Path
          value: "/vm63236"
        - name: Share_Path
          value: "/v2link"
